#!/usr/bin/env python
#
# Copyright 2011 Markus Pielmeier
#
# This file is part of roxappletbuilder2.
#
# roxappletbuilder2 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# roxappletbuilder2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with roxappletbuilder2.  If not, see <http://www.gnu.org/licenses/>.
#

from roxappletbuilder.main import main
from roxappletbuilder.state.states import State
from roxappletbuilder.state.app import StateApp
from roxappletbuilder.resource import ResourceResolver
import os

class DemoSwitchApp(StateApp):

    def _determineActiveState(self):
        # TODO
        return self.states[0]

    def __init__(self):
        cmd = 'sleep 1'

        states = [State(os.path.join('res', icon), cmd) for icon in ['BlueCircle.png', 'GreenSquare.png', 'OrangeCircle.png', 'OrangeSquare.png']]

        super(DemoSwitchApp, self).__init__('DemoSwitch', states, ResourceResolver(__file__))

if(__name__ == '__main__'):
    main(DemoSwitchApp())
