#!/usr/bin/env python
#
# Copyright 2011 Markus Pielmeier
#
# This file is part of roxappletbuilder2.
#
# roxappletbuilder2 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# roxappletbuilder2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with roxappletbuilder2.  If not, see <http://www.gnu.org/licenses/>.
#

from roxappletbuilder.main import main
from roxappletbuilder.state.states import State
from roxappletbuilder.state.app import StateApp

class LocaleSwitchApp(StateApp):
    # TODO separate UI and state logic into two artifacts

    def _determineActiveState(self):
        # TODO
        return self.states[0]

    def __init__(self):
        # TODO replace absolute image paths with image path resolution mechanism
        states = [
            State('/home/marook/work/images/icons/Flag_of_the_United_States.svg', '/home/marook/apps/scripts/switch_kb_en'),
            State('/home/marook/work/images/icons/Flag_of_Germany.svg', '/home/marook/apps/scripts/switch_kb_de')
            ]

        super(LocaleSwitchApp, self).__init__('LocaleSwitch', states)

if(__name__ == '__main__'):
    main(LocaleSwitchApp())
